runtime: php
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "8.2"

env: flex
entrypoint: gunicorn -b :$PORT main:app

service: v1.my-service.profileapp-endang

env_variables:
 CLOUD_STORAGE_BUCKET: [profileapp-endang]












# runtime: php
# env: flex
# entrypoint: gunicorn -b :$PORT main:app

# runtime_config:
#   operating_system: "ubuntu22"
#   # runtime_version: "8.2"

# #[START gae_flex_storage_yaml]
# env_variables:
#   CLOUD_STORAGE_BUCKET: [profileapp-endang]
#[END gae_flex_storage_yaml]


# resources:
#   cpu: 2
#   memory_gb: 2.3
#   disk_size_gb: 10
#   volumes:
#   - name: ramdisk1
#     volume_type: tmpfs
#     size_gb: 0.5

# runtime: php
# env: flex

# runtime_config:
#   document_root: public

# env_variables:
#   BUCKET_NAME: profileapp-endang

# handlers:
# - url: /static
#   static_dir: public/static
# - url: /(.+\.php)$
#   script: auto
